version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/mosheeshel/goreplay"